<?php

namespace ContainerXHqbtLE;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Jrld8MMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jrld8MM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jrld8MM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\TaskController::create' => ['privates', '.service_locator.fbK7LEM', 'get_ServiceLocator_FbK7LEMService', true],
            'App\\Controller\\TaskController::delete' => ['privates', '.service_locator.fbK7LEM', 'get_ServiceLocator_FbK7LEMService', true],
            'App\\Controller\\TaskController::index' => ['privates', '.service_locator.fbK7LEM', 'get_ServiceLocator_FbK7LEMService', true],
            'App\\Controller\\TaskController::toggle' => ['privates', '.service_locator.fbK7LEM', 'get_ServiceLocator_FbK7LEMService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\TaskController:create' => ['privates', '.service_locator.fbK7LEM', 'get_ServiceLocator_FbK7LEMService', true],
            'App\\Controller\\TaskController:delete' => ['privates', '.service_locator.fbK7LEM', 'get_ServiceLocator_FbK7LEMService', true],
            'App\\Controller\\TaskController:index' => ['privates', '.service_locator.fbK7LEM', 'get_ServiceLocator_FbK7LEMService', true],
            'App\\Controller\\TaskController:toggle' => ['privates', '.service_locator.fbK7LEM', 'get_ServiceLocator_FbK7LEMService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\TaskController::create' => '?',
            'App\\Controller\\TaskController::delete' => '?',
            'App\\Controller\\TaskController::index' => '?',
            'App\\Controller\\TaskController::toggle' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\TaskController:create' => '?',
            'App\\Controller\\TaskController:delete' => '?',
            'App\\Controller\\TaskController:index' => '?',
            'App\\Controller\\TaskController:toggle' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
