<?php

namespace ContainerXHqbtLE;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FbK7LEMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fbK7LEM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fbK7LEM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'taskService' => ['privates', 'App\\Service\\TaskService', 'getTaskServiceService', true],
        ], [
            'taskService' => 'App\\Service\\TaskService',
        ]);
    }
}
