<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXHqbtLE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXHqbtLE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXHqbtLE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXHqbtLE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXHqbtLE\App_KernelDevDebugContainer([
    'container.build_hash' => 'XHqbtLE',
    'container.build_id' => '96b5be75',
    'container.build_time' => 1683452973,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXHqbtLE');
